=begin
#Cielo24

#The cielo24 Web Services Platform API allows developers to easily integrate transcription, captioning and keyword extraction into their applications without having to use a manual web portal.

The version of the OpenAPI document: 1.0.0
Contact: devs@cielo24.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for cielo24::AddMediaResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe cielo24::AddMediaResponse do
  let(:instance) { cielo24::AddMediaResponse.new }

  describe 'test an instance of AddMediaResponse' do
    it 'should create an instance of AddMediaResponse' do
      expect(instance).to be_instance_of(cielo24::AddMediaResponse)
    end
  end
  describe 'test attribute "task_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
