=begin
#Cielo24

#The cielo24 Web Services Platform API allows developers to easily integrate transcription, captioning and keyword extraction into their applications without having to use a manual web portal.

The version of the OpenAPI document: 1.0.0
Contact: devs@cielo24.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for cielo24::IWPEnum
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe cielo24::IWPEnum do
  let(:instance) { cielo24::IWPEnum.new }

  describe 'test an instance of IWPEnum' do
    it 'should create an instance of IWPEnum' do
      expect(instance).to be_instance_of(cielo24::IWPEnum)
    end
  end
end
